# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=200)),
                ('cost', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=2000)),
                ('ad_type', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('balance', models.IntegerField(default=0)),
                ('university_name', models.CharField(max_length=100)),
                ('faculty_name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User'),
        ),
    ]
